services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_NAME=pos
    networks:
      - springboot-pos-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - springboot-pos-postgres
    environment:
      - POSTGRES_USER=posuser
      - POSTGRES_PASSWORD=posuser
      - POSTGRES_DB=pos
    expose:
      - 5432
volumes:
  db-data:
networks:
  springboot-pos-postgres: